POST https://node-do-zero-3y7f.onrender.com/videos
Content-Type: application/json

{
  "title": "Video novo online",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET https://node-do-zero-3y7f.onrender.com/videos

###

PUT https://node-do-zero-3y7f.onrender.com/videos/459434d5-c6e9-4524-adf9-b00f8c7c4c9e
Content-Type: application/json

{
  "title": "Teste Update",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###
DELETE https://node-do-zero-3y7f.onrender.com/videos/459434d5-c6e9-4524-adf9-b00f8c7c4c9e